jdbc.driverClassName=org.postgresql.Driver
jdbc.url=jdbc:postgresql://host.docker.internal:5432/petfriend?useSSL=false
jdbc.username=pet
jdbc.password=petpassword
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jpa.database = petfriend
hibernate.generate_statistics = true
hibernate.show_sql = true
jpa.generateDdl = true
jpa.showSql = true
